image: abstruse

matrix:
  - env: SCRIPT=shadowJar

before_install:
  - apt update

install:
  - apt install -y openjdk-8-jdk
  - apt install -y gradle

script:
  - if [[ "SCRIPT" ]]; then gradle $SCRIPT; fi