main: net.trivernis.chunkmaster.Chunkmaster
name: Chunkmaster
version: '0.10-beta-SNAPSHOT'
description: Chunk commands plugin.
author: Trivernis
website: trivernis.net
api-version: '1.14'
commands:
  chunkmaster:
    description: Main command
    permission: chunkmaster.chunkmaster
    usage: /chunkmaster <generate|list|pause|resume|cancel|reload>
    aliases:
      - chm
      - chunkm
      - cmaster
permissions:
  cunkmaster.generate:
    description: Allows the generate subcommand.
    default: op
  chunkmaster.list:
    description: Allows the list subcommand.
    default: op
  chunkmaster.cancel:
    description: Allows the remove subcommand.
    default: op
  chunkmaster.pause:
    description: Allows the pause subcommand.
    default: op
  chunkmaster.resume:
    description: Allows the resume subcommand.
    default: op
  chunkmaster.reload:
    description: Allows the reload subcommand.
    default: op
  chunkmaster.chunkmaster:
    description: Allows Chunkmaster commands.
    default: op
  chunkmaster.*:
    description: Wildcard permission
    default: op
    children:
      - chunkmaster.generate
      - chunkmaster.listgentasks
      - chunkmaster.removegentask
      - chunkmaster.pausegentasks
      - chunkmaster.resumegentasks
      - chunkmaster.chunkmaster