main: net.trivernis.chunkmaster.Chunkmaster
name: Chunkmaster
version: '1.0 SNAPSHOT'
description: Chunk commands plugin.
author: Trivernis
website: trivernis.net
api-version: '1.14'
commands:
  generate:
    description: Generates chunks starting from the world spawnpoint
    permission: chumkmaster.generate
    usage: /generate [world]
  listgentasks:
    description: Lists all generation tasks
    permission: chunkmaster.listgentasks
    usage: /listgentasks
  removegentask:
    description: Removes the generation task with the specified id
    permission: chunkmaster.removegentask
    usage: /removegentask {task-id}
permissions:
  cunkmaster.generate:
    description: Allows generate command.
    default: op
  chunkmaster.listgentasks:
    description: Allows the listgentask command.
    default: op
  chunkmaster.removegentask:
    description: Allows the removegentask command.
    default: op
  chunkmaster.*:
    description: Wildcard permission
    default: op
    children:
      - chunkmaster.generate
      - chunkmaster.listgentasks
      - chunkmaster.removegentask