name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: docker://gradle:latest
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew shadowJar
